# Generated by Django 3.2.7 on 2023-03-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_column='imageid')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.CharField(default='2000/01/01', max_length=45)),
                ('sex', models.CharField(default='male', max_length=45)),
                ('height', models.FloatField(default=0.0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.TextField(null=True)),
                ('userid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('pressures', models.IntegerField(db_column='pressureS', default=0)),
                ('pressured', models.IntegerField(db_column='pressureD', default=0)),
                ('heartbeat', models.IntegerField(default=0)),
                ('bmi', models.FloatField(default=0.0)),
                ('bmr', models.FloatField(default=0.0)),
                ('result1', models.CharField(default=True, max_length=100)),
                ('result2', models.CharField(default=True, max_length=100)),
                ('result3', models.CharField(default=True, max_length=100)),
                ('result4', models.CharField(default=True, max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
