# Generated by Django 3.2.7 on 2022-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221025_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_id',
            field=models.IntegerField(db_column='imageid', default=True),
        ),
    ]
