# Generated by Django 3.2.7 on 2022-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='birthday',
            field=models.CharField(default='2002/07/11', max_length=45),
        ),
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.IntegerField(default=177),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_id',
            field=models.IntegerField(db_column='imageid', default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='pressured',
            field=models.IntegerField(db_column='pressureD', default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='pressures',
            field=models.IntegerField(db_column='pressureS', default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='sex',
            field=models.CharField(default='male', max_length=45),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
