# Generated by Django 3.2.7 on 2022-11-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20221105_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
