# Generated by Django 3.2.7 on 2022-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('temperature', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('pressures', models.IntegerField(db_column='pressureS', default=0)),
                ('pressured', models.IntegerField(db_column='pressureD', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_column='imageid', default=0)),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.CharField(default='2002/07/11', max_length=45)),
                ('sex', models.CharField(default='male', max_length=45)),
                ('height', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
